import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: 'autogenerated', dirName: 'getting-started' },
    { type: 'autogenerated', dirName: 'user-guide' },
    { type: 'autogenerated', dirName: 'developers' },
    {
      type: 'category',
      label: 'SDK Reference',
      items: [
        { type: 'doc', id: 'api/index', label: 'Overview' },
        { type: 'autogenerated', dirName: 'api/plugin-sdk' },
        { type: 'autogenerated', dirName: 'api/theme-sdk' },
        { type: 'autogenerated', dirName: 'api/provider-sdk' },
        { type: 'autogenerated', dirName: 'api/contracts' },
      ],
    },
  ],
};

export default sidebars;
