#!/usr/bin/env node
/**
 * contract-codegen — deterministic code generator for the NeoTavern product wire contract.
 *
 * Inputs:
 *   - the built wire layer of `@neotavern/contracts`
 *     (`packages/contracts/dist/wire/index.js`), rebuilt here first via
 *     `pnpm --filter @neotavern/contracts build` so the tool always consumes fresh output.
 *     The wire layer exposes `buildProductWireRegistry()`, `compileWireContract`,
 *     `resolveFixtureSchemaId`, `WIRE_PROTOCOL`, `SCHEMA_DIALECT`, `FFI_ABI_VERSION`,
 *     `GENERATOR_VERSION` and `WIRE_FORMAT_PATTERNS`.
 *
 * Outputs (all canonical JSON unless noted):
 *   - packages/contracts/generated/contract.bundle.json — `{wireProtocol, schemaDialect,
 *     schemas:[...], operations:[...]}`; schemas are the canonical serialized TypeBox schemas
 *     (with $id), operations are the full compiled operation objects.
 *   - packages/contracts/generated/contract-manifest.json — protocol/dialect/schemaHash
 *     (sha256 of the emitted bundle bytes) + per-operation metadata map.
 *   - packages/contracts/generated/fixtures/<fixtureId>.json — one canonical JSON file per
 *     fixture, plus fixtures/corpus.json indexing them.
 *   - crates/contracts-generated/src/generated.rs — the Rust boundary DTO module.
 *
 * Determinism: canonical JSON is recursively key-sorted with no whitespace and a trailing
 * newline; generated.rs emits schemas in registry (registration) order with properties and
 * union members in schema order. Identical input therefore always produces byte-identical
 * output — run twice and diff.
 *
 * `--check` regenerates every output in memory and byte-compares it against the file on disk,
 * printing `OK <path>` / `DIFF <path>` per file and exiting 1 if anything differs, without
 * writing anything.
 */
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const REPO_ROOT = resolve(import.meta.dirname, '..', '..');
const WIRE_INDEX = join(REPO_ROOT, 'packages', 'contracts', 'dist', 'wire', 'index.js');

const HEADER = `// @generated by tools/contract-codegen/codegen.mjs — DO NOT EDIT.
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::sync::LazyLock;
use regex::Regex;
use crate::{Issue, WireError};
`;

// ---------------------------------------------------------------------------
// Canonical JSON
// ---------------------------------------------------------------------------

/**
 * Recursively sort object keys (arrays keep order), reject values that cannot be
 * represented deterministically, and return a plain JSON-ready structure.
 */
function sortJson(value) {
  if (value === null || typeof value === 'string' || typeof value === 'boolean') {
    return value;
  }
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) {
      throw new Error(`canonical JSON: non-finite number ${value} is not wire-safe`);
    }
    return value;
  }
  if (Array.isArray(value)) {
    return value.map((item) => {
      if (item === undefined) {
        throw new Error('canonical JSON: undefined inside an array is not wire-safe');
      }
      return sortJson(item);
    });
  }
  if (typeof value === 'object') {
    const out = {};
    for (const key of Object.keys(value).sort()) {
      const item = value[key];
      if (item === undefined) continue;
      out[key] = sortJson(item);
    }
    return out;
  }
  throw new Error(`canonical JSON: unsupported value of type ${typeof value}`);
}

/** Canonical JSON string: recursively key-sorted, no whitespace. */
function canonicalString(value) {
  return JSON.stringify(sortJson(value));
}

// ---------------------------------------------------------------------------
// Naming (rust-contract.md §3: strip leading `wire.`, split on `.`, kebab →
// snake/Pascal per segment, joined with `_` / nothing)
// ---------------------------------------------------------------------------

function pascalSegment(segment) {
  return segment
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function snakeOfId(id) {
  const segments = id.startsWith('wire.') ? id.slice('wire.'.length).split('.') : id.split('.');
  return segments.map((segment) => segment.replace(/-/g, '_')).join('_');
}

function pascalOfId(id) {
  const segments = id.startsWith('wire.') ? id.slice('wire.'.length).split('.') : id.split('.');
  return segments.map(pascalSegment).join('');
}

function snakeKey(key) {
  return key.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}

/** PascalCase of a discriminated value or inline key, e.g. `consumer_lagged` → `ConsumerLagged`. */
function pascalValue(value) {
  return pascalSegment(value);
}

/** Rust string literal content (escapes backslashes and quotes). */
function rustStr(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/** Rust numeric literal for a JSON number (f64 gets a `.0` suffix when integral). */
function rustNumber(value) {
  if (Number.isInteger(value)) return `${value}.0`;
  return String(value);
}

function isStringConst(member) {
  return (
    member !== null &&
    typeof member === 'object' &&
    member.type === 'string' &&
    typeof member.const === 'string'
  );
}

const RUST_KEYWORDS = new Set([
  'as',
  'async',
  'await',
  'break',
  'const',
  'continue',
  'crate',
  'dyn',
  'else',
  'enum',
  'extern',
  'false',
  'fn',
  'for',
  'if',
  'impl',
  'in',
  'let',
  'loop',
  'match',
  'mod',
  'move',
  'mut',
  'pub',
  'ref',
  'return',
  'self',
  'Self',
  'static',
  'struct',
  'super',
  'trait',
  'true',
  'type',
  'unsafe',
  'unsized',
  'use',
  'where',
  'while',
  'abstract',
  'become',
  'box',
  'do',
  'final',
  'macro',
  'override',
  'priv',
  'typeof',
  'virtual',
  'yield',
  'try',
  'union',
]);

/** Rust field identifier for a JSON key (raw identifier when the snake_case name is a keyword). */
function rustFieldName(key) {
  const snake = snakeKey(key);
  return RUST_KEYWORDS.has(snake) ? `r#${snake}` : snake;
}

// ---------------------------------------------------------------------------
// Rust type mapping
// ---------------------------------------------------------------------------

/**
 * Map a property schema to its Rust type. Inline (non-$id) objects become named
 * helper structs (`Pascal(parentId) + PascalField(key)`), collected into `helpers`
 * in first-use order so emission stays deterministic.
 */
function rustTypeFor(schema, ctx, suggestedName) {
  if (schema === null || typeof schema !== 'object') {
    throw new Error(`rustType: expected a schema object, got ${String(schema)}`);
  }
  if (typeof schema.$id === 'string') {
    if (ctx.registryIds.has(schema.$id)) return pascalOfId(schema.$id);
    throw new Error(`rustType: property references unknown $id "${schema.$id}"`);
  }
  if (Array.isArray(schema.anyOf)) {
    if (schema.anyOf.every(isStringConst)) return 'String';
    throw new Error(
      `rustType: inline anyOf that is not a closed string enum cannot be typed: ${canonicalString(schema)}`,
    );
  }
  switch (schema.type) {
    case 'string':
      return 'String';
    case 'integer':
      return 'i64';
    case 'number':
      return 'f64';
    case 'boolean':
      return 'bool';
    case 'null':
      return 'Value';
    case 'object': {
      const keys = Object.keys(schema.properties ?? {});
      const ap = schema.additionalProperties;
      if (keys.length === 0) {
        if (ap === true) return 'Value';
        if (ap !== null && typeof ap === 'object') {
          return `HashMap<String, ${rustPrimitiveType(ap)}>`;
        }
        throw new Error(
          `rustType: empty strict object without $id cannot be typed: ${canonicalString(schema)}`,
        );
      }
      return helperFor(schema, suggestedName, ctx);
    }
    case 'array': {
      const items = schema.items;
      if (items === null || typeof items !== 'object') {
        throw new Error(`rustType: array without an items schema: ${canonicalString(schema)}`);
      }
      return `Vec<${rustTypeFor(items, ctx, suggestedName)}>`;
    }
    default:
      throw new Error(`rustType: unsupported schema: ${canonicalString(schema)}`);
  }
}

function rustPrimitiveType(schema) {
  if (schema === null || typeof schema !== 'object') {
    throw new Error(`rustPrimitiveType: expected a schema object, got ${String(schema)}`);
  }
  switch (schema.type) {
    case 'string':
      return 'String';
    case 'integer':
      return 'i64';
    case 'number':
      return 'f64';
    case 'boolean':
      return 'bool';
    default:
      throw new Error(
        `rustPrimitiveType: unsupported map value schema: ${canonicalString(schema)}`,
      );
  }
}

function helperFor(schema, suggestedName, ctx) {
  if (typeof suggestedName !== 'string' || suggestedName.length === 0) {
    throw new Error('helperFor: inline object needs a contextual type name');
  }
  const typeName = suggestedName;
  // Only the struct is emitted: property checks inline the object logic (helpers have no
  // registered $id, so per §3 there is no check_<child> delegation), and emitting an
  // unused checker would trip rustc's dead_code lint.
  ctx.helpers.push({ typeName, structLines: emitStructLines(schema, typeName, ctx) });
  return typeName;
}

// ---------------------------------------------------------------------------
// Rust emission — checker bodies
// ---------------------------------------------------------------------------

/**
 * Expression for passing a path into `join_path(path: &str, key: &str)`: the root `path`
 * parameter is already `&str`; locals (`child_path`/`key_path`/`item_path`) are `String`
 * and must be borrowed explicitly (no auto-ref coercion at call sites).
 */
function joinPathExpr(p, keyExpr) {
  return p === 'path' ? `join_path(path, ${keyExpr})` : `join_path(&${p}, ${keyExpr})`;
}

/**
 * Expression for a path passed to `Issue::new(impl Into<String>, ...)`: the root `path`
 * parameter is `&str` (cheap, Into<String> works); local `String`s must be borrowed via
 * `as_str()` or each use would move them (E0382).
 */
function issuePathExpr(p) {
  return p === 'path' ? p : `${p}.as_str()`;
}

/** Register a regex static for the current check fn; returns its name (RE_<n>). */
function ensureRegex(pattern, ctx) {
  const name = `RE_${ctx.staticIndex.n++}`;
  ctx.statics.push({ name, pattern });
  return name;
}

function emitNodeCheck(schema, v, p, ctx, ind, isRoot = false) {
  if (schema === null || typeof schema !== 'object') {
    throw new Error(`checker: expected a schema object, got ${String(schema)}`);
  }
  if (!isRoot && typeof schema.$id === 'string' && ctx.registryIds.has(schema.$id)) {
    return [`${ind}check_${snakeOfId(schema.$id)}(${v}, &${p}, issues);`];
  }
  if (Array.isArray(schema.anyOf)) {
    if (schema.anyOf.every(isStringConst)) return emitEnumCheck(schema, v, p, ind);
    if (typeof schema['x-wire-discriminator'] === 'string' && schema['x-wire-discriminator']) {
      return emitDiscriminatedCheck(schema, v, p, ctx, ind);
    }
    throw new Error(
      `checker: unsupported anyOf (not a closed string enum, no discriminator): ${canonicalString(schema)}`,
    );
  }
  switch (schema.type) {
    case 'string':
      return emitStringCheck(schema, v, p, ctx, ind);
    case 'integer':
      return emitIntegerCheck(schema, v, p, ind);
    case 'number':
      return emitNumberCheck(schema, v, p, ind);
    case 'boolean':
      return [
        `${ind}if !${v}.is_boolean() {`,
        `${ind}    issues.push(Issue::new(${issuePathExpr(p)}, "Boolean"));`,
        `${ind}}`,
      ];
    case 'null':
      return [
        `${ind}if !${v}.is_null() {`,
        `${ind}    issues.push(Issue::new(${issuePathExpr(p)}, "Null"));`,
        `${ind}}`,
      ];
    case 'object':
      return emitObjectCheck(schema, v, p, ctx, ind);
    case 'array':
      return emitArrayCheck(schema, v, p, ctx, ind);
    default:
      throw new Error(
        `checker: unsupported schema type ${JSON.stringify(schema.type)}: ${canonicalString(schema)}`,
      );
  }
}

function emitStringCheck(schema, v, p, ctx, ind) {
  const ind1 = ind + '    ';
  const ind2 = ind + '        ';
  const hasMinLength = typeof schema.minLength === 'number' && schema.minLength > 0;
  const hasMaxLength = typeof schema.maxLength === 'number';
  const inner = [];
  if (hasMinLength) {
    inner.push(
      `${ind2}if len < ${schema.minLength} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "StringMinLength"));`,
      `${ind2}}`,
    );
  }
  if (hasMaxLength) {
    inner.push(
      `${ind2}if len > ${schema.maxLength} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "StringMaxLength"));`,
      `${ind2}}`,
    );
  }
  if (typeof schema.pattern === 'string') {
    const re = ensureRegex(schema.pattern, ctx);
    inner.push(
      `${ind2}if !${re}.is_match(s) {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "StringPattern"));`,
      `${ind2}}`,
    );
  }
  if (typeof schema.format === 'string') {
    const pattern = ctx.formatPatterns[schema.format];
    if (typeof pattern !== 'string') {
      throw new Error(`checker: unregistered wire format "${schema.format}"`);
    }
    const re = ensureRegex(pattern, ctx);
    inner.push(
      `${ind2}if !${re}.is_match(s) {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "StringFormat"));`,
      `${ind2}}`,
    );
  }
  if (typeof schema.const === 'string') {
    inner.push(
      `${ind2}if s != ${JSON.stringify(schema.const)} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "StringConst"));`,
      `${ind2}}`,
    );
  }
  const lines = [
    `${ind}match ${v}.as_str() {`,
    `${ind1}Some(${inner.length > 0 ? 's' : '_s'}) => {`,
  ];
  if (inner.length > 0) {
    if (hasMinLength || hasMaxLength) {
      lines.push(`${ind2}let len = s.encode_utf16().count();`);
    }
    lines.push(...inner);
  }
  lines.push(
    `${ind1}}`,
    `${ind1}None => issues.push(Issue::new(${issuePathExpr(p)}, "String")),`,
    `${ind}}`,
  );
  return lines;
}

function emitIntegerCheck(schema, v, p, ind) {
  const ind1 = ind + '    ';
  const ind2 = ind + '        ';
  const inner = [];
  if (typeof schema.minimum === 'number') {
    inner.push(
      `${ind2}if n < ${schema.minimum} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "IntegerMinimum"));`,
      `${ind2}}`,
    );
  }
  if (typeof schema.maximum === 'number') {
    inner.push(
      `${ind2}if n > ${schema.maximum} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "IntegerMaximum"));`,
      `${ind2}}`,
    );
  }
  if (typeof schema.const === 'number') {
    inner.push(
      `${ind2}if n != ${schema.const} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "IntegerConst"));`,
      `${ind2}}`,
    );
  }
  const lines = [
    `${ind}match ${v}.as_i64() {`,
    `${ind1}Some(${inner.length > 0 ? 'n' : '_n'}) => {`,
  ];
  lines.push(...inner);
  lines.push(
    `${ind1}}`,
    `${ind1}None => issues.push(Issue::new(${issuePathExpr(p)}, "Integer")),`,
    `${ind}}`,
  );
  return lines;
}

function emitNumberCheck(schema, v, p, ind) {
  const ind1 = ind + '    ';
  const ind2 = ind + '        ';
  const inner = [];
  if (typeof schema.minimum === 'number') {
    inner.push(
      `${ind2}if n < ${rustNumber(schema.minimum)} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "NumberMinimum"));`,
      `${ind2}}`,
    );
  }
  if (typeof schema.maximum === 'number') {
    inner.push(
      `${ind2}if n > ${rustNumber(schema.maximum)} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "NumberMaximum"));`,
      `${ind2}}`,
    );
  }
  if (typeof schema.const === 'number') {
    inner.push(
      `${ind2}if n != ${rustNumber(schema.const)} {`,
      `${ind2}    issues.push(Issue::new(${issuePathExpr(p)}, "NumberConst"));`,
      `${ind2}}`,
    );
  }
  const lines = [
    `${ind}match ${v}.as_f64() {`,
    `${ind1}Some(${inner.length > 0 ? 'n' : '_n'}) => {`,
  ];
  lines.push(...inner);
  lines.push(
    `${ind1}}`,
    `${ind1}None => issues.push(Issue::new(${issuePathExpr(p)}, "Number")),`,
    `${ind}}`,
  );
  return lines;
}

function emitObjectCheck(schema, v, p, ctx, ind) {
  const ind1 = ind + '    ';
  const ind2 = ind + '        ';
  const ind3 = ind + '            ';
  const props = schema.properties ?? {};
  const keys = Object.keys(props);
  const ap = schema.additionalProperties;
  const tolerant = ap === true;
  const mapSchema = ap !== null && typeof ap === 'object' ? ap : null;
  const required = Array.isArray(schema.required) ? schema.required : [];
  const lines = [
    `${ind}if !${v}.is_object() {`,
    `${ind1}issues.push(Issue::new(${issuePathExpr(p)}, "Object"));`,
    `${ind}} else {`,
  ];
  if (tolerant) {
    lines.push(`${ind}}`);
    return lines;
  }
  if (mapSchema) {
    lines.push(
      `${ind1}if let Some(obj) = ${v}.as_object() {`,
      `${ind2}for (key, val) in obj {`,
      `${ind3}let key_path = ${joinPathExpr(p, 'key')};`,
      ...emitNodeCheck(mapSchema, 'val', 'key_path', ctx, ind3),
      `${ind2}}`,
      `${ind1}}`,
      `${ind}}`,
    );
    return lines;
  }
  for (const key of required) {
    if (!props[key]) {
      throw new Error(
        `checker: required key "${key}" is not a property of ${canonicalString(schema)}`,
      );
    }
    lines.push(
      `${ind1}if ${v}.get(${JSON.stringify(key)}).is_none() {`,
      `${ind2}issues.push(Issue::new(${joinPathExpr(p, JSON.stringify(key))}, "RequiredProperty"));`,
      `${ind1}}`,
    );
  }
  for (const key of keys) {
    lines.push(
      `${ind1}if let Some(child) = ${v}.get(${JSON.stringify(key)}) {`,
      `${ind2}let child_path = ${joinPathExpr(p, JSON.stringify(key))};`,
      ...emitNodeCheck(props[key], 'child', 'child_path', ctx, ind2),
      `${ind1}}`,
    );
  }
  lines.push(`${ind1}if let Some(obj) = ${v}.as_object() {`, `${ind2}for key in obj.keys() {`);
  if (keys.length === 0) {
    // Empty strict object: every present key is unknown.
    lines.push(
      `${ind3}let key_path = ${joinPathExpr(p, 'key')};`,
      `${ind3}issues.push(Issue::new(key_path.as_str(), "AdditionalProperties"));`,
    );
  } else {
    lines.push(
      `${ind3}if !matches!(key.as_str(), ${keys.map((key) => JSON.stringify(key)).join(' | ')}) {`,
      `${ind3}    let key_path = ${joinPathExpr(p, 'key')};`,
      `${ind3}    issues.push(Issue::new(key_path.as_str(), "AdditionalProperties"));`,
      `${ind3}}`,
    );
  }
  lines.push(`${ind2}}`, `${ind1}}`, `${ind}}`);
  return lines;
}

function emitArrayCheck(schema, v, p, ctx, ind) {
  const ind1 = ind + '    ';
  const ind2 = ind + '        ';
  const items = schema.items;
  if (items === null || typeof items !== 'object') {
    throw new Error(`checker: array without an items schema: ${canonicalString(schema)}`);
  }
  const lines = [
    `${ind}if !${v}.is_array() {`,
    `${ind1}issues.push(Issue::new(${issuePathExpr(p)}, "Array"));`,
    `${ind}} else if let Some(arr) = ${v}.as_array() {`,
  ];
  if (typeof schema.minItems === 'number') {
    lines.push(
      `${ind1}if arr.len() < ${schema.minItems} {`,
      `${ind2}issues.push(Issue::new(${issuePathExpr(p)}, "ArrayMinItems"));`,
      `${ind1}}`,
    );
  }
  if (typeof schema.maxItems === 'number') {
    lines.push(
      `${ind1}if arr.len() > ${schema.maxItems} {`,
      `${ind2}issues.push(Issue::new(${issuePathExpr(p)}, "ArrayMaxItems"));`,
      `${ind1}}`,
    );
  }
  lines.push(
    `${ind1}for (i, item) in arr.iter().enumerate() {`,
    `${ind2}let item_path = format!("{}[{}]", ${p}, i);`,
    ...emitNodeCheck(items, 'item', 'item_path', ctx, ind2),
    `${ind1}}`,
    `${ind}}`,
  );
  return lines;
}

function emitEnumCheck(schema, v, p, ind) {
  const ind1 = ind + '    ';
  const ind2 = ind + '        ';
  const ind3 = ind + '            ';
  const values = schema.anyOf.map((member) => member.const);
  return [
    `${ind}match ${v}.as_str() {`,
    `${ind1}Some(s) => {`,
    `${ind2}if !matches!(s, ${values.map((value) => JSON.stringify(value)).join(' | ')}) {`,
    `${ind3}issues.push(Issue::new(${issuePathExpr(p)}, "Union"));`,
    `${ind2}}`,
    `${ind1}}`,
    `${ind1}None => issues.push(Issue::new(${issuePathExpr(p)}, "String")),`,
    `${ind}}`,
  ];
}

// ---------------------------------------------------------------------------
// Canonical JSON
// ---------------------------------------------------------------------------

/**
 * Recursively sort object keys (arrays keep order), reject values that cannot be
 * represented deterministically, and return a plain JSON-ready structure.
 */
function emitDiscriminatedCheck(schema, v, p, ctx, ind) {
  const ind1 = ind + '    ';
  const ind2 = ind + '        ';
  const ind3 = ind + '            ';
  const disc = schema['x-wire-discriminator'];
  const lines = [
    `${ind}let tag = ${v}.get(${JSON.stringify(disc)}).and_then(|t| t.as_str());`,
    `${ind}match tag {`,
  ];
  for (const member of schema.anyOf) {
    if (member === null || typeof member !== 'object' || typeof member.properties !== 'object') {
      throw new Error(
        `checker: discriminator member is not an object schema: ${canonicalString(member)}`,
      );
    }
    const constValue = member.properties[disc]?.const;
    if (typeof constValue !== 'string') {
      throw new Error(
        `checker: discriminator member missing string const at "${disc}": ${canonicalString(member)}`,
      );
    }
    const props = member.properties;
    const memberKeys = Object.keys(props);
    const checkKeys = memberKeys.filter((key) => key !== disc);
    const memberRequired = Array.isArray(member.required) ? member.required : [];
    const required = memberRequired.filter((key) => key !== disc);
    lines.push(`${ind1}Some(${JSON.stringify(constValue)}) => {`);
    for (const key of required) {
      if (!props[key]) {
        throw new Error(`checker: discriminator member requires unknown key "${key}"`);
      }
      lines.push(
        `${ind2}if ${v}.get(${JSON.stringify(key)}).is_none() {`,
        `${ind3}issues.push(Issue::new(${joinPathExpr(p, JSON.stringify(key))}, "RequiredProperty"));`,
        `${ind2}}`,
      );
    }
    for (const key of checkKeys) {
      lines.push(
        `${ind2}if let Some(child) = ${v}.get(${JSON.stringify(key)}) {`,
        `${ind3}let child_path = ${joinPathExpr(p, JSON.stringify(key))};`,
        ...emitNodeCheck(props[key], 'child', 'child_path', ctx, ind3),
        `${ind2}}`,
      );
    }
    lines.push(`${ind2}if let Some(obj) = ${v}.as_object() {`, `${ind3}for key in obj.keys() {`);
    if (memberKeys.length === 0) {
      lines.push(
        `${ind3}    let key_path = ${joinPathExpr(p, 'key')};`,
        `${ind3}    issues.push(Issue::new(key_path.as_str(), "AdditionalProperties"));`,
      );
    } else {
      lines.push(
        `${ind3}    if !matches!(key.as_str(), ${memberKeys.map((key) => JSON.stringify(key)).join(' | ')}) {`,
        `${ind3}        let key_path = ${joinPathExpr(p, 'key')};`,
        `${ind3}        issues.push(Issue::new(key_path.as_str(), "AdditionalProperties"));`,
        `${ind3}    }`,
      );
    }
    lines.push(`${ind3}}`, `${ind2}}`, `${ind1}}`);
  }
  lines.push(
    `${ind1}_ => issues.push(Issue::new(${issuePathExpr(p)}, "Discriminator")),`,
    `${ind}}`,
  );
  return lines;
}

// ---------------------------------------------------------------------------
// Rust emission — structs / enums / check / validate / decode
// ---------------------------------------------------------------------------

function emitStructLines(schema, typeName, ctx) {
  const props = schema.properties ?? {};
  const required = Array.isArray(schema.required) ? new Set(schema.required) : null;
  const ap = schema.additionalProperties;
  const tolerant = ap === true;
  const lines = ['#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]'];
  if (!tolerant) {
    lines.push('#[serde(deny_unknown_fields)]');
  }
  if (tolerant) {
    lines.push(`pub struct ${typeName} {`, '    pub payload: Value,', '}');
    return lines;
  }
  const fieldLines = [];
  for (const [key, prop] of Object.entries(props)) {
    const fieldName = rustFieldName(key);
    const optional = required === null || !required.has(key);
    const serdeOptions = [];
    if (snakeKey(key) !== key) serdeOptions.push(`rename = "${rustStr(key)}"`);
    if (optional) serdeOptions.push('default', 'skip_serializing_if = "Option::is_none"');
    const ty = rustTypeFor(prop, ctx, `${typeName}${pascalValue(key)}`);
    if (serdeOptions.length > 0) {
      fieldLines.push(`    #[serde(${serdeOptions.join(', ')})]`);
    }
    fieldLines.push(`    pub ${fieldName}: ${optional ? `Option<${ty}>` : ty},`);
  }
  if (fieldLines.length === 0) {
    lines.push(`pub struct ${typeName} {}`);
  } else {
    lines.push(`pub struct ${typeName} {`, ...fieldLines, '}');
  }
  return lines;
}

function emitEnumLines(schema, typeName) {
  const lines = [
    '#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]',
    `pub enum ${typeName} {`,
  ];
  for (const member of schema.anyOf) {
    lines.push(
      `    #[serde(rename = ${JSON.stringify(member.const)})] ${pascalValue(member.const)},`,
    );
  }
  lines.push('}');
  return lines;
}

function emitTaggedEnumLines(schema, typeName, ctx) {
  const disc = schema['x-wire-discriminator'];
  const lines = [
    '#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]',
    `#[serde(tag = "${disc}")]`,
    `pub enum ${typeName} {`,
  ];
  for (const member of schema.anyOf) {
    const constValue = member.properties[disc]?.const;
    if (typeof constValue !== 'string') {
      throw new Error(`tagged enum ${typeName}: member missing string const at "${disc}"`);
    }
    const fieldEntries = Object.entries(member.properties ?? {}).filter(([key]) => key !== disc);
    const variantName = pascalValue(constValue);
    if (fieldEntries.length === 0) {
      lines.push(`    #[serde(rename = ${JSON.stringify(constValue)})] ${variantName},`);
    } else {
      const required = Array.isArray(member.required) ? new Set(member.required) : null;
      const fields = fieldEntries.map(([key, prop]) => {
        const fieldName = rustFieldName(key);
        const serdeOptions = [];
        if (snakeKey(key) !== key) serdeOptions.push(`rename = "${rustStr(key)}"`);
        const optional = required === null || !required.has(key);
        if (optional) serdeOptions.push('default', 'skip_serializing_if = "Option::is_none"');
        const ty = rustTypeFor(prop, ctx, `${typeName}${pascalValue(key)}`);
        const attr = serdeOptions.length > 0 ? `#[serde(${serdeOptions.join(', ')})] ` : '';
        return `${attr}${fieldName}: ${optional ? `Option<${ty}>` : ty}`;
      });
      lines.push(
        `    #[serde(rename = ${JSON.stringify(constValue)})] ${variantName} { ${fields.join(', ')} },`,
      );
    }
  }
  lines.push('}');
  return lines;
}

function emitCheckerForSchema(schema, snakeName, ctx) {
  const fnCtx = { ...ctx, statics: [], staticIndex: { n: 0 } };
  const body = emitNodeCheck(schema, 'value', 'path', fnCtx, '    ', true);
  const statics = fnCtx.statics.map(
    (s) =>
      `static ${s.name}: LazyLock<Regex> = LazyLock::new(|| Regex::new("${rustStr(s.pattern)}").unwrap_or_else(|_| Regex::new("$^").unwrap()));`,
  );
  return [
    `pub(crate) fn check_${snakeName}(value: &Value, path: &str, issues: &mut Vec<Issue>) {`,
    ...statics.map((line) => `    ${line}`),
    ...body,
    '}',
  ];
}

function emitValidateDecode(snakeName, typeName) {
  return [
    `pub fn validate_${snakeName}(value: &Value) -> Result<(), Vec<Issue>> {`,
    '    let mut issues = Vec::new();',
    `    check_${snakeName}(value, "", &mut issues);`,
    '    if issues.is_empty() { Ok(()) } else { Err(issues) }',
    '}',
    '',
    `pub fn decode_${snakeName}(bytes: &[u8]) -> Result<${typeName}, WireError> {`,
    `    crate::decode::<${typeName}>(validate_${snakeName}, bytes)`,
    '}',
  ];
}

function emitTopLevelSchema(schema, ctx) {
  const id = schema.$id;
  if (typeof id !== 'string' || id.length === 0) {
    throw new Error(`registry schema without $id: ${canonicalString(schema)}`);
  }
  const snakeName = snakeOfId(id);
  const typeName = pascalOfId(id);
  const lines = [];
  if (Array.isArray(schema.anyOf)) {
    if (schema.anyOf.every(isStringConst)) {
      lines.push(...emitEnumLines(schema, typeName));
    } else if (
      typeof schema['x-wire-discriminator'] === 'string' &&
      schema['x-wire-discriminator']
    ) {
      lines.push(...emitTaggedEnumLines(schema, typeName, ctx));
    } else {
      throw new Error(`registry schema ${id}: unsupported anyOf shape`);
    }
  } else if (schema.type === 'object') {
    lines.push(...emitStructLines(schema, typeName, ctx));
  } else {
    throw new Error(
      `registry schema ${id}: unsupported top-level type ${JSON.stringify(schema.type)}`,
    );
  }
  lines.push(
    '',
    ...emitCheckerForSchema(schema, snakeName, ctx),
    '',
    ...emitValidateDecode(snakeName, typeName),
  );
  if (id === 'wire.error.dto') {
    // Alias matching the wire-design export name ProductErrorDto ($id wire.error.dto).
    lines.push(
      '',
      '/// Alias for `ErrorDto` (wire-design name for `wire.error.dto`).',
      'pub type ProductErrorDto = ErrorDto;',
    );
  }
  if (id === 'wire.request.empty') {
    // Kernel dispatch contract (rust-contract.md §5) references decode_empty_request_dto.
    lines.push(
      '',
      '/// Kernel-contract alias for `decode_request_empty`.',
      'pub fn decode_empty_request_dto(bytes: &[u8]) -> Result<RequestEmpty, WireError> {',
      '    crate::decode::<RequestEmpty>(validate_request_empty, bytes)',
      '}',
    );
  }
  if (id === 'wire.result.empty') {
    lines.push(
      '',
      '/// Kernel-contract alias for `decode_result_empty`.',
      'pub fn decode_empty_result_dto(bytes: &[u8]) -> Result<ResultEmpty, WireError> {',
      '    crate::decode::<ResultEmpty>(validate_result_empty, bytes)',
      '}',
    );
  }
  return lines;
}

function emitGeneratedRs(registryIds, operations, schemas, formatPatterns) {
  const ctx = {
    registryIds,
    formatPatterns,
    helpers: [],
    staticIndex: { n: 0 },
    statics: [],
  };
  const mainBlocks = [];
  for (const schema of schemas) {
    mainBlocks.push(emitTopLevelSchema(schema, ctx).join('\n'));
  }
  const helperBlocks = ctx.helpers.map((helper) => helper.structLines.join('\n'));
  const joinPath = [
    'fn join_path(path: &str, key: &str) -> String {',
    '    format!("{}{}{}", path, if path.is_empty() { "" } else { "/" }, key)',
    '}',
  ].join('\n');
  return [
    HEADER.trimEnd(),
    joinPath,
    emitLimits(operations),
    ...helperBlocks,
    ...mainBlocks,
  ].join('\n\n') + '\n';
}

/**
 * Emits the per-operation byte limits as generated Rust (plan rev 2.2
 * Layer C): `operation_request_limit` / `operation_response_limit` plus the
 * registry-wide maxima used as defaults. Single source of truth — the
 * numbers come from the registry here, exactly like the manifest, so no
 * hand-written 1 MiB / 16 MiB constants can drift.
 */
function emitLimits(operations) {
  const reqMax = Math.max(...operations.map((op) => op.requestLimitBytes));
  const respMax = Math.max(...operations.map((op) => op.responseLimitBytes));
  const reqLines = operations.map((op) => `        "${op.operationId}" => Some(${op.requestLimitBytes}),`);
  const respLines = operations.map((op) => `        "${op.operationId}" => Some(${op.responseLimitBytes}),`);
  return [
    '/// The maximum request byte limit across the registry (generated).',
    `pub const DEFAULT_REQUEST_LIMIT_BYTES: u64 = ${reqMax};`,
    '/// The maximum response byte limit across the registry (generated).',
    `pub const DEFAULT_RESPONSE_LIMIT_BYTES: u64 = ${respMax};`,
    '',
    '/// The wire request byte limit for `operation_id` (generated from the',
    '/// registry; `None` for an operation that is not part of the contract).',
    'pub fn operation_request_limit(operation_id: &str) -> Option<u64> {',
    '    match operation_id {',
    ...reqLines,
    '        _ => None,',
    '    }',
    '}',
    '',
    '/// The wire response byte limit for `operation_id` (generated from the',
    '/// registry; `None` for an operation that is not part of the contract).',
    'pub fn operation_response_limit(operation_id: &str) -> Option<u64> {',
    '    match operation_id {',
    ...respLines,
    '        _ => None,',
    '    }',
    '}',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Outputs
// ---------------------------------------------------------------------------

function buildOutputs(registry, wire) {
  const { operations, schemas } = registry;
  const fixtures = Array.isArray(registry.fixtures)
    ? registry.fixtures
    : wire.PRODUCT_WIRE_FIXTURES;
  if (!Array.isArray(fixtures)) {
    throw new Error(
      'wire layer exposes neither `buildProductWireRegistry().fixtures` nor ' +
        '`PRODUCT_WIRE_FIXTURES`; the WireFixture[] list is required to generate the corpus',
    );
  }
  const { compileWireContract, WIRE_PROTOCOL, SCHEMA_DIALECT, FFI_ABI_VERSION, GENERATOR_VERSION } =
    wire;
  // Re-run compilation as a sanity gate; it throws ContractCompileError on any violation.
  compileWireContract({ operations, fixtures }, schemas);

  const bundle = {
    wireProtocol: WIRE_PROTOCOL,
    schemaDialect: SCHEMA_DIALECT,
    schemas: [...schemas.values()],
    operations,
  };
  const bundleText = canonicalString(bundle) + '\n';
  const schemaHash = createHash('sha256').update(bundleText, 'utf8').digest('hex');

  const manifest = {
    wireProtocol: WIRE_PROTOCOL,
    schemaDialect: SCHEMA_DIALECT,
    schemaHash,
    ffiAbiVersion: FFI_ABI_VERSION,
    generatorVersion: GENERATOR_VERSION,
    operations: Object.fromEntries(
      operations.map((op) => [
        op.operationId,
        {
          feature: op.feature,
          version: op.version,
          executionClass: op.executionClass,
          idempotency: op.idempotency,
          retryPolicy: op.retryPolicy,
          authScope: op.authScope,
          requestSchemaId: op.requestSchemaId,
          ...(op.responseSchemaId !== undefined ? { responseSchemaId: op.responseSchemaId } : {}),
          ...(op.eventSchemaId !== undefined ? { eventSchemaId: op.eventSchemaId } : {}),
          allowedErrorCodes: op.allowedErrorCodes,
          requestLimitBytes: op.requestLimitBytes,
          responseLimitBytes: op.responseLimitBytes,
          ...(op.eventLimitBytes !== undefined ? { eventLimitBytes: op.eventLimitBytes } : {}),
          unknownFields: op.unknownFields,
        },
      ]),
    ),
  };

  const corpus = fixtures.map((fixture) => ({
    id: fixture.id,
    operationId: fixture.operationId,
    kind: fixture.kind,
    schemaId: wire.resolveFixtureSchemaId(fixture, operations),
    valid: fixture.valid,
    file: `${fixture.id}.json`,
  }));

  const outputs = {};
  outputs['packages/contracts/generated/contract.bundle.json'] = bundleText;
  outputs['packages/contracts/generated/contract-manifest.json'] = canonicalString(manifest) + '\n';
  outputs['packages/contracts/generated/fixtures/corpus.json'] = canonicalString(corpus) + '\n';
  for (const fixture of fixtures) {
    outputs[`packages/contracts/generated/fixtures/${fixture.id}.json`] =
      canonicalString(fixture.value) + '\n';
  }
  const registryIds = new Set(schemas.keys());
  outputs['crates/contracts-generated/src/generated.rs'] = emitGeneratedRs(
    registryIds,
    operations,
    schemas.values(),
    wire.WIRE_FORMAT_PATTERNS,
  );
  return outputs;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function writeAtomic(absPath, content) {
  const tmpPath = `${absPath}.tmp-${process.pid}`;
  writeFileSync(tmpPath, content, 'utf8');
  try {
    renameSync(tmpPath, absPath);
  } catch (err) {
    // Windows: rename over an existing file is rejected; replace it first.
    if (err && (err.code === 'EPERM' || err.code === 'EEXIST')) {
      rmSync(absPath, { force: true });
      renameSync(tmpPath, absPath);
    } else {
      throw err;
    }
  }
}

/** 64-hex `WIRE_SCHEMA_HASH` literal from packages/contracts/src/wire/manifest.ts, or null. */
function readWireSchemaHash() {
  const tsPath = join(REPO_ROOT, 'packages', 'contracts', 'src', 'wire', 'manifest.ts');
  if (!existsSync(tsPath)) return null;
  const match = /WIRE_SCHEMA_HASH\s*=\s*['"]([0-9a-fA-F]{64})['"]/.exec(
    readFileSync(tsPath, 'utf8'),
  );
  return match ? match[1].toLowerCase() : null;
}

async function main() {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');
  const unknown = args.filter((arg) => arg !== '--check');
  if (unknown.length > 0) {
    console.error(
      `[contract-codegen] usage: node codegen.mjs [--check] (unknown args: ${unknown.join(' ')})`,
    );
    process.exit(2);
  }

  console.log('[contract-codegen] building @neotavern/contracts wire layer…');
  execSync('pnpm --filter @neotavern/contracts build', { cwd: REPO_ROOT, stdio: 'inherit' });

  const wire = await import(pathToFileURL(WIRE_INDEX).href);
  const requiredExports = [
    'buildProductWireRegistry',
    'compileWireContract',
    'resolveFixtureSchemaId',
    'WIRE_PROTOCOL',
    'SCHEMA_DIALECT',
    'FFI_ABI_VERSION',
    'GENERATOR_VERSION',
    'WIRE_FORMAT_PATTERNS',
  ];
  const missing = requiredExports.filter((name) => wire[name] === undefined);
  if (missing.length > 0) {
    throw new Error(`wire dist missing required exports: ${missing.join(', ')}`);
  }
  if (typeof wire.WIRE_FORMAT_PATTERNS !== 'object' || wire.WIRE_FORMAT_PATTERNS === null) {
    throw new Error('wire dist WIRE_FORMAT_PATTERNS must be an object');
  }

  const registry = wire.buildProductWireRegistry();
  const outputs = buildOutputs(registry, wire);

  const computedHash = JSON.parse(
    outputs['packages/contracts/generated/contract-manifest.json'],
  ).schemaHash;
  const sourceHash = readWireSchemaHash();
  const hashOk = sourceHash !== null && sourceHash === computedHash;
  const hashDetail =
    sourceHash === null
      ? 'WIRE_SCHEMA_HASH literal not found in packages/contracts/src/wire/manifest.ts'
      : `manifest.ts WIRE_SCHEMA_HASH ${sourceHash} != generated ${computedHash}`;

  if (checkOnly) {
    let failed = false;
    for (const [relPath, content] of Object.entries(outputs)) {
      const absPath = join(REPO_ROOT, relPath);
      let same = false;
      if (existsSync(absPath)) {
        same = readFileSync(absPath, 'utf8') === content;
      }
      console.log(`${same ? 'OK' : 'DIFF'} ${relPath}`);
      if (!same) failed = true;
    }
    if (hashOk) {
      console.log('OK packages/contracts/src/wire/manifest.ts (WIRE_SCHEMA_HASH matches)');
    } else {
      console.log(`DIFF packages/contracts/src/wire/manifest.ts (${hashDetail})`);
      failed = true;
    }
    const summary = failed
      ? '[contract-codegen] --check FAILED: outputs differ from disk'
      : '[contract-codegen] --check OK: outputs match disk';
    console.log(summary);
    process.exit(failed ? 1 : 0);
  }

  for (const [relPath, content] of Object.entries(outputs)) {
    const absPath = join(REPO_ROOT, relPath);
    mkdirSync(dirname(absPath), { recursive: true });
    writeAtomic(absPath, content);
    console.log(`[contract-codegen] wrote ${relPath}`);
  }
  if (!hashOk) {
    console.warn(`[contract-codegen] WARNING: ${hashDetail}`);
  }
  console.log('[contract-codegen] done.');
}

if (import.meta.main) {
  main().catch((err) => {
    console.error(`[contract-codegen] ${err && err.stack ? err.stack : String(err)}`);
    process.exit(1);
  });
}

// Exported for the verification harness (tools are run via `node codegen.mjs`, so these
// exports are inert in normal use).
export { buildOutputs, canonicalString, emitGeneratedRs, pascalOfId, snakeOfId };
