/**
 * Design tokens (theme level 1). Semantic CSS custom properties prefixed with
 * `--st-`. Components must reference these tokens — never hardcoded values
 * (AGENTS.md §14 / ТЗ §6.3). Themes override any subset; the defaults below
 * guarantee every token resolves.
 */

export const TOKEN_PREFIX = '--st-';

/**
 * Canonical semantic token names (without the `--st-` prefix). This is the
 * stable, versioned theming contract.
 */
export const TOKEN_NAMES = [
  // Colors — text
  'color-text-primary',
  'color-text-secondary',
  'color-text-muted',
  'color-text-inverse',
  'color-text-link',
  // Colors — surfaces
  'color-surface-primary',
  'color-surface-secondary',
  'color-surface-tertiary',
  'color-surface-overlay',
  'color-surface-canvas',
  'color-surface-elevated',
  // Colors — accent & status
  'color-accent',
  'color-accent-hover',
  'color-accent-text',
  'color-accent-soft',
  'color-accent-soft-text',
  'color-border',
  'color-border-subtle',
  'color-border-strong',
  'color-success',
  'color-warning',
  'color-danger',
  'color-info',
  // Colors — chat message markdown (ST1-compatible roleplay formatting)
  'color-message-quote',
  'color-message-emphasis',
  'color-message-code',
  'color-message-code-bg',
  // Typography
  'font-ui',
  'font-mono',
  'font-size-2xs',
  'font-size-xs',
  'font-size-sm',
  'font-size-md',
  'font-size-lg',
  'font-size-xl',
  'font-size-2xl',
  'line-height-body',
  'font-weight-normal',
  'font-weight-medium',
  'font-weight-semibold',
  'font-weight-strong',
  'font-weight-bold',
  // Spacing
  'space-2xs',
  'space-xs',
  'space-sm',
  'space-md',
  'space-lg',
  'space-xl',
  'space-2xl',
  'space-3xl',
  // Radii
  'radius-control',
  'radius-card',
  'radius-overlay',
  'radius-panel',
  'radius-round',
  'radius-inset',
  // Borders
  'border-width',
  // Elevation
  'shadow-card',
  'shadow-soft',
  'shadow-focus',
  'shadow-overlay',
  // Layers (z-index)
  'layer-base',
  'layer-raised',
  'layer-panel',
  'layer-plugin-overlay',
  'layer-plugin-chrome',
  'layer-dropdown',
  'layer-modal',
  'layer-notification',
  // Motion
  'motion-duration-fast',
  'motion-duration-normal',
  'motion-duration-slow',
  'motion-easing-standard',
  'effect-glass-blur',
  // Control sizes
  'control-height',
  'control-height-large',
  'control-height-sm',
  'control-height-xs',
  'control-height-2xs',
  'control-hit-min',
  'switch-width',
  'switch-height',
  'switch-thumb-size',
  'menu-min-width',
  'dialog-max-width',
  'dialog-max-height',
  'textarea-min-height',
  'spinner-size',
  // Panel and content sizes
  'size-panel-max-height',
  'size-content-max-height',
  'size-chat-column-max',
  // Viewport limits
  'overlay-width-limit',
  'overlay-height-limit',
  'dialog-sheet-height',
  // Scrollbars
  'scrollbar-width',
  'scrollbar-radius',
  'scrollbar-track-bg',
  'scrollbar-thumb-bg',
  'scrollbar-thumb-hover-bg',
  'scrollbar-fade-duration',
  'scrollbar-fade-easing',
  'scrollbar-hide-delay',
  // App shell sizes
  'shell-rail-width',
  'shell-panel-width',
  'shell-panel-min-width',
  'shell-panel-max-width',
  // Chat canvas
  'chat-wallpaper-image',
  'chat-wallpaper-position',
  'chat-wallpaper-size',
  'chat-wallpaper-overlay',
  'chat-wallpaper-blur',
  // User-adjustable glass/wallpaper knobs (set at runtime by theme/apply.ts)
  'custom-glass-blur',
  'custom-ui-opacity',
  'custom-wallpaper-overlay-alpha',
  // Chat typography metrics (overridden by chat-style presets)
  'chat-markdown-column-width',
  'chat-message-block',
  'chat-message-inline',
] as const;

export type TokenName = (typeof TOKEN_NAMES)[number];
export type TokenSet = Partial<Record<TokenName, string>>;
export type ResolvedTokenSet = Record<TokenName, string>;

export const DEFAULT_LIGHT_TOKENS: ResolvedTokenSet = {
  'color-text-primary': '#26221f',
  'color-text-secondary': '#5c554f',
  'color-text-muted': '#706861',
  'color-text-inverse': '#ffffff',
  'color-text-link': '#8d4026',
  'color-surface-primary': '#fbfaf8',
  'color-surface-secondary': '#f3f0eb',
  'color-surface-tertiary': '#e9e4dc',
  'color-surface-overlay': '#ffffff',
  'color-surface-canvas': '#eee9e2',
  'color-surface-elevated': '#ffffff',
  'color-accent': '#984729',
  'color-accent-hover': '#7d351d',
  'color-accent-text': '#ffffff',
  'color-accent-soft': '#f1ded4',
  'color-accent-soft-text': '#6f2e19',
  'color-border': '#ddd6cd',
  'color-border-subtle': '#eae5df',
  'color-border-strong': '#aaa097',
  'color-success': '#2d7b4c',
  'color-warning': '#a86118',
  'color-danger': '#b23b35',
  'color-info': '#416f83',
  // Light-mode message colors meet WCAG 2.2 AA (4.5:1) on the chat surface.
  'color-message-quote': '#96520e',
  'color-message-emphasis': '#6e6e6e',
  'color-message-code': '#5c554f',
  'color-message-code-bg': '#e9e4dc',
  'font-ui': "'Outfit Variable', 'Segoe UI Variable', sans-serif",
  'font-mono': "'JetBrains Mono Variable', 'Cascadia Code', monospace",
  'font-size-2xs': '0.6875rem',
  'font-size-xs': '0.75rem',
  'font-size-sm': '0.8125rem',
  'font-size-md': '1rem',
  'font-size-lg': '1.25rem',
  'font-size-xl': '1.75rem',
  'font-size-2xl': '2.125rem',
  'line-height-body': '1.45',
  'font-weight-normal': '400',
  'font-weight-medium': '500',
  'font-weight-semibold': '600',
  'font-weight-strong': '650',
  'font-weight-bold': '700',
  'space-2xs': '2px',
  'space-xs': '4px',
  'space-sm': '8px',
  'space-md': '12px',
  'space-lg': '16px',
  'space-xl': '24px',
  'space-2xl': '32px',
  'space-3xl': '48px',
  'radius-control': '10px',
  'radius-card': '16px',
  'radius-overlay': '20px',
  'radius-panel': '28px',
  'radius-round': '999px',
  'radius-inset': '4px',
  'border-width': '1px',
  'shadow-card': '0 1px 2px rgba(68, 54, 43, 0.08)',
  'shadow-soft': '0 8px 24px rgba(68, 54, 43, 0.09)',
  'shadow-focus': '0 0 0 3px rgba(152, 71, 41, 0.16)',
  'shadow-overlay': '0 24px 64px rgba(45, 35, 28, 0.22)',
  'layer-base': '0',
  'layer-raised': '1',
  'layer-panel': '100',
  'layer-plugin-overlay': '200',
  'layer-plugin-chrome': '300',
  'layer-dropdown': '1100',
  'layer-modal': '1000',
  'layer-notification': '1500',
  'motion-duration-fast': '180ms',
  'motion-duration-normal': '320ms',
  'motion-duration-slow': '1400ms',
  'motion-easing-standard': 'cubic-bezier(0.22, 1, 0.36, 1)',
  'effect-glass-blur': 'var(--st-custom-glass-blur, 16px)',
  'control-height': '44px',
  'control-height-large': '52px',
  'control-height-sm': '40px',
  'control-height-xs': '36px',
  'control-height-2xs': '32px',
  'control-hit-min': '44px',
  'switch-width': '40px',
  'switch-height': '22px',
  'switch-thumb-size': '18px',
  'menu-min-width': '200px',
  'dialog-max-width': '560px',
  'dialog-max-height': '85vh',
  'textarea-min-height': '96px',
  'spinner-size': '20px',
  'size-panel-max-height': '70vh',
  'size-content-max-height': '20rem',
  'size-chat-column-max': '1080px',
  'overlay-width-limit': '92vw',
  'overlay-height-limit': '60vh',
  'dialog-sheet-height': '88dvh',
  'scrollbar-width': '8px',
  'scrollbar-radius': '999px',
  'scrollbar-track-bg': 'transparent',
  'scrollbar-thumb-bg': 'color-mix(in srgb, var(--st-color-border-strong) 45%, transparent)',
  'scrollbar-thumb-hover-bg': 'color-mix(in srgb, var(--st-color-accent) 65%, transparent)',
  'scrollbar-fade-duration': '320ms',
  'scrollbar-fade-easing': 'cubic-bezier(0.22, 1, 0.36, 1)',
  'scrollbar-hide-delay': '1000ms',
  'shell-rail-width': '60px',
  'shell-panel-width': '380px',
  'shell-panel-min-width': '260px',
  'shell-panel-max-width': '720px',
  'chat-wallpaper-image': 'none',
  'chat-wallpaper-position': 'center',
  'chat-wallpaper-size': 'cover',
  'chat-wallpaper-overlay': 'rgba(251, 250, 248, var(--st-custom-wallpaper-overlay-alpha, 0.4))',
  'chat-wallpaper-blur': '0px',
  'custom-glass-blur': '16px',
  'custom-ui-opacity': '70%',
  'custom-wallpaper-overlay-alpha': '0.4',
  'chat-markdown-column-width': '75ch',
  'chat-message-block': 'var(--st-space-md)',
  'chat-message-inline': 'var(--st-space-md)',
};

export const DEFAULT_DARK_TOKENS: ResolvedTokenSet = {
  ...DEFAULT_LIGHT_TOKENS,
  'color-text-primary': '#f3eee8',
  'color-text-secondary': '#c5bbb2',
  'color-text-muted': '#998f87',
  'color-text-inverse': '#211b17',
  'color-text-link': '#f0a07d',
  'color-surface-primary': '#1b1917',
  'color-surface-secondary': '#24211e',
  'color-surface-tertiary': '#302c28',
  'color-surface-overlay': '#292522',
  'color-surface-canvas': '#151311',
  'color-surface-elevated': '#292522',
  'color-accent': '#e38a62',
  'color-accent-hover': '#f09a73',
  'color-accent-text': '#2a130b',
  'color-accent-soft': '#492a20',
  'color-accent-soft-text': '#ffc4a8',
  'color-border': '#39342f',
  'color-border-subtle': '#2b2723',
  'color-border-strong': '#625a53',
  // Status colors need their own dark palette: the light values only reach
  // 2.7–3.7:1 on dark surfaces (WCAG AA wants 4.5:1 for text).
  'color-success': '#63c98d',
  'color-warning': '#e0a35c',
  'color-danger': '#f0837d',
  'color-info': '#7fb3c9',
  // Dark-mode message colors meet WCAG 2.2 AA (4.5:1) on the chat surface.
  'color-message-quote': '#e8943a',
  'color-message-emphasis': '#919191',
  'color-message-code': '#c5bbb2',
  'color-message-code-bg': '#302c28',
  'shadow-card': '0 1px 2px rgba(0, 0, 0, 0.35)',
  'shadow-soft': '0 10px 28px rgba(0, 0, 0, 0.26)',
  'shadow-focus': '0 0 0 3px rgba(227, 138, 98, 0.2)',
  'shadow-overlay': '0 24px 64px rgba(0, 0, 0, 0.58)',
  'chat-wallpaper-overlay': 'rgba(18, 16, 14, var(--st-custom-wallpaper-overlay-alpha, 0.3))',
  'custom-wallpaper-overlay-alpha': '0.3',
};
